name: Build and Release

# 添加必要的权限
permissions:
  contents: write
  packages: write
  pull-requests: read

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          # Windows on ARM64 is not commonly used
          - goos: windows
            goarch: arm64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        # Get version info
        VERSION=${GITHUB_REF_NAME:-dev}
        BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        GIT_COMMIT=${GITHUB_SHA::7}
        
        # Set binary name with extension for Windows
        BINARY_NAME=wordma
        if [ "$GOOS" = "windows" ]; then
          BINARY_NAME="${BINARY_NAME}.exe"
        fi
        
        # Create output directory
        mkdir -p dist
        
        # Build binary with version info (临时文件名包含平台信息)
        LDFLAGS="-s -w -X main.Version=${VERSION} -X main.BuildTime=${BUILD_TIME} -X main.GitCommit=${GIT_COMMIT}"
        TEMP_BINARY="dist/temp-${BINARY_NAME}-${GOOS}-${GOARCH}"
        if [ "$GOOS" = "windows" ]; then
          TEMP_BINARY="${TEMP_BINARY}.exe"
        fi
        go build -ldflags="${LDFLAGS}" -o "${TEMP_BINARY}" .
        
        # Create archive with clean binary name
        cd dist
        if [ "$GOOS" = "windows" ]; then
          # 重命名为简洁的文件名并压缩
          mv "temp-${BINARY_NAME}-${GOOS}-${GOARCH}.exe" "${BINARY_NAME}"
          zip "wordma-${GOOS}-${GOARCH}.zip" "${BINARY_NAME}"
          rm "${BINARY_NAME}"  # 清理临时文件
        else
          # 重命名为简洁的文件名并压缩
          mv "temp-${BINARY_NAME}-${GOOS}-${GOARCH}" "${BINARY_NAME}"
          tar -czf "wordma-${GOOS}-${GOARCH}.tar.gz" "${BINARY_NAME}"
          rm "${BINARY_NAME}"  # 清理临时文件
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wordma-${{ matrix.goos }}-${{ matrix.goarch }}
        path: dist/wordma-${{ matrix.goos }}-${{ matrix.goarch }}.*
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}